version: '3.7'
services:
  softum-api:
    build:
      context: .
      dockerfile: './Dockerfile'
    ports:
      - '${APP_PORT}:3000'
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${DB_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: